-- Products table schema for Supabase
create table products (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  sku varchar(100) not null unique,
  category varchar(100) not null,
  stock_level integer not null default 0,
  max_stock integer not null default 100,
  buy_price numeric(12, 2) not null,
  sell_price numeric(12, 2) not null,
  icon varchar(100) not null default 'inventory_2',
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table products enable row level security;

-- Create policy for public read/write access
create policy "Allow public access" on products for all to public using (true);

-- Insert seed data
insert into products (name, sku, category, stock_level, max_stock, buy_price, sell_price, icon) values
  ('MacBook Pro M2 - 14"', 'ELC-MBP-14-M2', 'Electronics', 42, 50, '1850.00', '2299.00', 'devices'),
  ('Premium Cotton T-Shirt (L)', 'CLO-TSH-COT-L', 'Clothing', 8, 50, '12.50', '34.99', 'checkroom'),
  ('Organic Coffee Beans (1kg)', 'FOD-COF-ORG-1K', 'Food', 124, 130, '18.20', '42.00', 'restaurant'),
  ('Wireless Noise Cancelling Headphones', 'ELC-WNC-HDP-BK', 'Electronics', 15, 50, '120.00', '249.99', 'headphones'),
  ('Ergonomic Office Chair', 'FUR-ERG-CHR-01', 'Furniture', 33, 40, '280.00', '549.00', 'chair'),
  ('Smart Watch Pro Series', 'ELC-SWP-GLD-42', 'Electronics', 5, 30, '180.00', '399.99', 'watch'),
  ('Italian Leather Belt (M)', 'CLO-BLT-LTH-M', 'Clothing', 67, 80, '22.00', '64.99', 'checkroom'),
  ('Extra Virgin Olive Oil (500ml)', 'FOD-OIL-EVO-5H', 'Food', 200, 250, '8.50', '19.99', 'restaurant'),
  ('4K Ultra HD Monitor - 27"', 'ELC-MON-4K-27', 'Electronics', 0, 25, '350.00', '599.99', 'monitor'),
  ('Running Shoes Pro (Size 10)', 'CLO-SHO-RUN-10', 'Clothing', 45, 60, '65.00', '139.99', 'checkroom'),
  ('Standing Desk Converter', 'FUR-DSK-STD-01', 'Furniture', 12, 20, '150.00', '299.00', 'desk'),
  ('Bluetooth Speaker Portable', 'ELC-SPK-BT-RD', 'Electronics', 78, 100, '25.00', '59.99', 'speaker'),
  ('Organic Green Tea (100 bags)', 'FOD-TEA-GRN-1H', 'Food', 3, 50, '6.00', '14.99', 'restaurant'),
  ('Winter Parka Jacket (XL)', 'CLO-JKT-PRK-XL', 'Clothing', 18, 30, '85.00', '199.99', 'checkroom'),
  ('USB-C Docking Station', 'ELC-DCK-USC-01', 'Electronics', 55, 70, '45.00', '89.99', 'dock'),
  ('Bamboo Cutting Board Set', 'FUR-KIT-BCB-ST', 'Furniture', 90, 100, '12.00', '29.99', 'kitchen'),
  ('Wireless Gaming Mouse', 'ELC-MOU-WGM-BK', 'Electronics', 2, 40, '35.00', '79.99', 'mouse'),
  ('Dark Chocolate Bar (200g)', 'FOD-CHO-DRK-2H', 'Food', 150, 200, '3.50', '8.99', 'restaurant'),
  ('Cashmere Scarf (Unisex)', 'CLO-SCR-CSH-UN', 'Clothing', 22, 35, '40.00', '99.99', 'checkroom'),
  ('Mechanical Keyboard RGB', 'ELC-KBD-MEC-RG', 'Electronics', 31, 50, '55.00', '129.99', 'keyboard'),
  ('Protein Powder Vanilla (2kg)', 'FOD-PRO-VAN-2K', 'Food', 7, 40, '25.00', '54.99', 'restaurant'),
  ('Bookshelf 5-Tier Walnut', 'FUR-BSH-WLN-05', 'Furniture', 9, 15, '120.00', '249.00', 'shelves'),
  ('Webcam 1080p HD', 'ELC-WEB-1080-HD', 'Electronics', 40, 60, '30.00', '69.99', 'videocam'),
  ('Denim Jeans Slim Fit (32)', 'CLO-JNS-SLM-32', 'Clothing', 56, 80, '28.00', '69.99', 'checkroom'),
  ('Almond Butter Organic (500g)', 'FOD-BUT-ALM-5H', 'Food', 0, 60, '7.00', '16.99', 'restaurant');